### PR TITLE
Revert "add facebook like button and youtube subscribe button"

### PR DESCRIPTION
**Pull request by sam17**
Reverts quadrotor-IITKgp/quadrotor-IITKgp.github.io#43

### CODE REVIEW

**Comment by sam17** [comment]
@shivangag  Shift the buttons to just below the ARK description box in home screen.

**Comment by shivangag** [comment]
Should I create a new PR for master branch or revert-43-gh-pages?

**Comment by sam17** [comment]
Push your commits in this pr if you can.

**Comment by shivangag** [comment]
I don't think I can, this is the PR created by you.

**Comment by sam17** [comment]
Send a new PR.

**Pull request merged**
