### PR TITLE
Revamp page design

### PR DESCRIPTION
**Pull request by shivangag**
See the changes at http://www.shivangagrawal.in/quadrotor-IITKgp.github.io/

### CODE REVIEW

**Comment by sam17** [comment]
Awesome work. Did you use progressive jpegs?
Also, change the descriptions of team members. I am an alum now for one. And remove redundant people from team?

**Comment by sam17** [comment]
That rotating gear in the middle is so cool 🗡

**Comment by shivangag** [comment]
@sam17 Yeah I've used progressive jpegs. And I'm working on other issues, will resolve them in days to come.

**Comment by shivangag** [comment]
Should we merge this?

**Pull request merged**
