### PR TITLE
add google analytics

### LINKED ISSUE #40: Google Analytics
Use ARK email ID to create a dashboard and inject Google Analytics code to the website.

### PR DESCRIPTION
**Pull request by shivangag**
closes #40

### CODE REVIEW

**Comment by sam17** [comment]
Give link to `dashboard` and add to `Readme`.

**Comment by shivangag** [comment]
[This](https://analytics.google.com/analytics/web/#dashboard) is the link to dashboard.

**Comment by sam17** [comment]
Which email ID has been used to create this?

**Comment by shivangag** [comment]
ARK's email ID aerialroboticskharagpur@gmail.com

**Comment by sam17** [comment]
Add link to `Readme`.

**Comment by shivangag** [comment]
Done.

**Pull request merged**
