### PR TITLE
Added Akshay's Image

### PR DESCRIPTION
**Pull request by aks-oo7**

### CODE REVIEW

**Comment by amanchandra333** [comment]
@aks-oo7 you duplicated the image of @manadmishra and removed that of @Gauraviitkgp . Make the necessary changes and open a PR again.

**Comment by Gauraviitkgp** [comment]
I reverted it back to original state

Regards,
*Gaurav Suryawanshi,*
Second Year Undergraduate,
Department of Mathematics,
IIT Kharagpur,

**Comment by Gauraviitkgp** [comment]
Hi guys,
This time we are gonna have our work a bit different as we are running into
multiple projects now. Moreover Phase II has a different way of getting
reimbursement. We've made a google drive Reimbursement
<https://drive.google.com/drive/folders/1f1TCvYXBGC2K8s94vqX0wLKzGAZy_mTd?usp=sharing>,
wherein all your details will go.Hence the system we are gonna follow are
as follows:-

1) All  *cash bills* of small article are to be put inside the *letter
box*(brown
wooden one) with your name written at the back. It would automatically be
reimbursed in the next Reimbursement

2) All bills which you've *ordered* and shipment has been received are to
be put inside* bills folder*. *Follow the instructions carefully.*

3) Simultaneously generate the *bank statement* of your order and put it in*
bank statements folder*. *Follow the instructions carefully.*

4) All things with high cost are required to be put in Quotations folder.
We'll update you with the instructions of this folder shortly.

*Failing* to above instructions will lead to *cancellation* of
reimbursement. We're keeping the process clean and more transparent this
time.

Regards,
*Gaurav Suryawanshi,*
3rd Year Undergraduate ,
Department of Mathematics,
IIT Kharagpur, *9409493648*

**Comment by Gauraviitkgp** [comment]
Everybody upload your pending bills ASAP

https://drive.google.com/drive/folders/1f1TCvYXBGC2K8s94vqX0wLKzGAZy_mTd?usp=sharing
Regards,
*Gaurav Suryawanshi,*
Third Year Undergraduate,
Mathematics and Computing,
IIT Kharagpur,
Mob:-+91-9409493648, Facebook
<https://www.facebook.com/gaurav.suryawanshi.88>, LinkedIn
<https://www.linkedin.com/in/gaurav-suryawanshi-b2017286/?lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_jobs%3B9ok%2BR0lmSB2Fu6YVehJ%2BDA%3D%3D&licu=urn%3Ali%3Acontrol%3Ad_flagship3_search_srp_jobs-nav.settings_view_profile>

**Pull request merged**
